learnity/core/urls.py
from django.urls import path

from core.views import (
    BookCreateView,
    BookDeleteView,
    BookJourneyCreateView,
    BookJourneyReadView,
    BookListView,
    BookPublishView,
    BookReadView,
    BookUpdateView,
    ChapterCreateView,
    ChapterDeleteView,
    ChapterJourneyCreateView,
    ChapterJourneyReadView,
    ChapterUpdateView,
    OwnBookListView,
)

app_name = 'core'
urlpatterns = [
    # books
    path('books/', BookListView.as_view(), name='book_list'),
    path('books/own/', OwnBookListView.as_view(), name='own_book_list'),
    path('books/add', BookCreateView.as_view(), name='book_create'),
    path('books/<int:pk>/', BookReadView.as_view(), name='book_read'),
    path('books/<int:pk>/edit', BookUpdateView.as_view(), name='book_update'),
    path('books/<int:pk>/publish', BookPublishView.as_view(), name='book_publish'),
    path('books/<int:pk>/delete', BookDeleteView.as_view(), name='book_delete'),
    # chapters
    path('books/<int:book_pk>/chapters/add', ChapterCreateView.as_view(), name='chapter_create'),
    path('books/<int:book_pk>/chapters/<int:pk>/edit', ChapterUpdateView.as_view(), name='chapter_update'),
    path('books/<int:book_pk>/chapters/<int:pk>/delete', ChapterDeleteView.as_view(), name='chapter_delete'),
    # book-journeys
    path('book/<int:book_pk>/start-journey', BookJourneyCreateView.as_view(), name='book_journey_create'),
    path('book-journeys/<uuid:pk>/', BookJourneyReadView.as_view(), name='book_journey_read'),
    # chapter-journeys
    path(
        'book-journeys/<uuid:book_journey_pk>/chapters/<int:chapter_pk>/start-journey',
        ChapterJourneyCreateView.as_view(),
        name='chapter_journey_create',
    ),
    path('chapter-journeys/<uuid:pk>/', ChapterJourneyReadView.as_view(), name='chapter_journey_read'),
]

learnity/learnity/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.views import HomeView, LoginView, LogoutView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('home/', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
]

learnity/core/models.py
import datetime
import uuid
from collections import defaultdict
from typing import Optional

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from . import utils


class Book(models.Model):

    _meta: models.options.Options
    abstract: str
    book_journey_set: models.manager.Manager
    chapter_set: models.manager.Manager
    created_at: datetime.datetime
    created_by_id: int
    deleted_at: Optional[datetime.datetime]
    description: str
    objects: models.manager.Manager
    published_at: Optional[datetime.datetime]
    subtitle: Optional[str]
    title: str
    url: str

    title = models.CharField(_('title'), max_length=64)
    subtitle = models.CharField(_('subtitle'), max_length=128, blank=True)
    abstract = models.CharField(_('abstract'), max_length=255)
    url = models.URLField(_('url'))
    description = models.TextField(_('description'))
    created_at = models.DateTimeField(_('creation timestamp'), blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_('creator'), blank=True, on_delete=models.PROTECT
    )
    published_at = models.DateTimeField(_('publication timestamp'), blank=True, null=True)
    deleted_at = models.DateTimeField(_('deletion timestamp'), blank=True, null=True)

    def __str__(self):
        return f'Book: {self.title}'

    def get_absolute_url(self):
        return reverse('core:book_read', kwargs={'pk': self.pk})

    def is_owned_by(self, user):
        return self.created_by_id == user.pk

    def can_be_deleted_by(self, user):
        return self.is_owned_by(user)

    def delete(self, *args, **kwargs):
        if kwargs.get('hard', False):
            return super().delete()

        self.deleted_at = utils.ticker.now()
        if kwargs.get('commit', True):
            self.save()

        # delete chapters and compile deletion info for return
        deletion_info = defaultdict(int)
        deletion_info[self._meta.label] += 1
        for chapter in self.get_chapters():
            _, info = chapter.delete(*args, **kwargs)
            for k, v in info.items():
                deletion_info[k] += v

        return sum(deletion_info.values()), dict(deletion_info)

    def is_deleted(self):
        return self.deleted_at is not None

    def can_be_published_by(self, user):
        return self.is_owned_by(user)

    def publish(self, *args, **kwargs):
        self.published_at = utils.ticker.now()
        if kwargs.get('commit', True):
            self.save()

    def is_published(self):
        return self.published_at is not None

    def has_chapters(self):
        return self.get_chapters().exists()

    def get_chapters(self):
        return self.chapter_set.filter(deleted_at__isnull=True)

    def get_book_journeys(self):
        return self.book_journey_set.filter(deleted_at__isnull=True)

    def has_book_journeys(self):
        return self.get_book_journeys().exists()

    def _get_book_journeys_by_user(self, user):
        return self.get_book_journeys().filter(created_by_id=user.pk)

    def has_book_journey_by_user(self, user):
        return self._get_book_journeys_by_user(user).exists()

    def get_book_journey_by_user(self, user):
        return self._get_book_journeys_by_user(user).get()


class Chapter(models.Model):

    _meta: models.options.Options
    book: Book
    book_id: int
    created_at: datetime.datetime
    deleted_at: Optional[datetime.datetime]
    description: str
    number: int
    objects: models.manager.Manager
    title: str
    url: Optional[str]

    number = models.PositiveSmallIntegerField(_('chapter number'))
    title = models.CharField(_('chapter title'), max_length=64)
    url = models.URLField(_('chapter URL'), blank=True)
    description = models.TextField(_('chapter description'), blank=True)
    created_at = models.DateTimeField(_('creation timestamp'), blank=True)
    deleted_at = models.DateTimeField(_('deletion timestamp'), blank=True, null=True)
    book = models.ForeignKey('core.Book', verbose_name=_('book'), blank=True, on_delete=models.PROTECT)

    def __str__(self):
        return f'Chapter: {self.title}'

    def clean(self):
        super().clean()
        if self.book_id is None:
            return
        for chapter in self.book.get_chapters():
            if chapter.pk != self.pk and chapter.number == self.number:
                raise ValidationError(_('A chapter with this number already exists on the same book'), code='invalid')

    def get_absolute_url(self):
        return reverse('core:book_read', kwargs={'pk': self.book_id}) + '?tab=chapters'

    def can_be_deleted_by(self, user):
        return self.book.is_owned_by(user)

    def delete(self, *args, **kwargs):
        if kwargs.get('hard', False):
            return super().delete()

        self.deleted_at = utils.ticker.now()
        if kwargs.get('commit', True):
            self.save()

        return 1, {self._meta.label: 1}

    def is_deleted(self):
        return self.deleted_at is not None


class BookJourney(models.Model):

    _meta: models.options.Options
    book: Book
    book_id: int
    chapter_journey_set: models.manager.Manager
    created_at: datetime.datetime
    created_by_id: int
    deleted_at: Optional[datetime.datetime]
    objects: models.manager.Manager
    uuid: str

    class Meta:
        verbose_name = 'book journey'

    uuid = models.UUIDField(_('UUID'), default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    book = models.ForeignKey(
        'core.Book', verbose_name=_('book'), blank=True, on_delete=models.PROTECT, related_name='book_journey_set'
    )
    created_at = models.DateTimeField(_('creation timestamp'), blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_('creator'), blank=True, on_delete=models.PROTECT
    )
    deleted_at = models.DateTimeField(_('deletion timestamp'), blank=True, null=True)

    def clean(self):
        super().clean()
        if self.book_id is None or self.created_by_id is None:
            return
        if BookJourney.objects.filter(
            ~Q(pk=self.pk), deleted_at__isnull=True, book_id=self.book_id, created_by_id=self.created_by_id
        ).exists():
            raise ValidationError(_('This user already has a book journey on the underlying book'), code='invalid')

    def can_be_deleted_by(self, user):
        return user.pk == self.created_by_id

    def delete(self, *args, **kwargs):
        if kwargs.get('hard', False):
            return super().delete()

        self.deleted_at = utils.ticker.now()
        if kwargs.get('commit', True):
            self.save()

        # delete chapter-journeys and compile deletion info for return
        deletion_info = defaultdict(int)
        deletion_info[self._meta.label] += 1
        for chapter_journey in self.get_chapter_journeys():
            _, info = chapter_journey.delete(*args, **kwargs)
            for k, v in info.items():
                deletion_info[k] += v

        return sum(deletion_info.values()), dict(deletion_info)

    def is_deleted(self):
        return self.deleted_at is not None

    def get_absolute_url(self):
        return reverse('core:book_journey_read', kwargs={'pk': self.pk})

    def is_owned_by(self, user):
        return self.created_by_id == user.pk

    def has_chapter_journeys(self):
        return self.get_chapter_journeys().exists()

    def get_chapter_journeys(self):
        return self.chapter_journey_set.filter(deleted_at__isnull=True)

    def _get_chapter_journeys_for_chapter(self, chapter: Chapter):
        return self.get_chapter_journeys().filter(chapter_id=chapter.pk)

    def has_chapter_journey_for_chapter(self, chapter: Chapter):
        return self._get_chapter_journeys_for_chapter(chapter).exists()

    def get_chapter_journey_for_chapter(self, chapter: Chapter):
        return self._get_chapter_journeys_for_chapter(chapter).get()


class ChapterJourney(models.Model):

    _meta: models.options.Options
    book_journey: BookJourney
    book_journey_id: str
    chapter: Chapter
    chapter_id: int
    created_at: datetime.datetime
    deleted_at: Optional[datetime.datetime]
    objects: models.manager.Manager
    uuid: str

    class Meta:
        verbose_name = 'chapter journey'

    uuid = models.UUIDField(_('UUID'), default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    book_journey = models.ForeignKey(
        'core.BookJourney',
        verbose_name=_('book journey'),
        blank=True,
        on_delete=models.PROTECT,
        related_name='chapter_journey_set',
    )
    chapter = models.ForeignKey('core.Chapter', verbose_name=_('chapter'), blank=True, on_delete=models.PROTECT)
    created_at = models.DateTimeField(_('creation timestamp'), blank=True)
    deleted_at = models.DateTimeField(_('deletion timestamp'), blank=True, null=True)

    def clean(self):
        super().clean()
        if self.book_journey_id is None or self.chapter_id is None:
            return
        if ChapterJourney.objects.filter(
            ~Q(pk=self.pk),
            deleted_at__isnull=True,
            book_journey__created_by_id=self.book_journey.created_by_id,
            chapter_id=self.chapter_id,
        ).exists():
            raise ValidationError(
                _('This user already has a chapter journey on the underlying chapter'), code='invalid'
            )

    def get_absolute_url(self):
        return reverse('core:chapter_journey_read', kwargs={'pk': self.pk})

    def is_owned_by(self, user):
        return self.book_journey.is_owned_by(user)

    def can_be_deleted_by(self, user):
        return self.is_owned_by(user)

    def delete(self, *args, **kwargs):
        if kwargs.get('hard', False):
            return super().delete()

learnity/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Chapter


class ChapterCreateForm(forms.ModelForm):
    class Meta:
        fields = ['number', 'title', 'url', 'description']
        model = Chapter

    def __init__(self, *args, **kwargs):
        self.book = kwargs.pop('book')
        super().__init__(*args, **kwargs)

    def clean_number(self):
        cleaned_number = self.cleaned_data['number']
        for chapter in self.book.get_chapters():
            if chapter.number == cleaned_number:
                raise ValidationError(_('A chapter with this number already exists on the same book'), code='invalid')
        return cleaned_number

learnity/core/templates/core/book_create.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'create a book' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="text-center h2 text-muted mb-4">{% translate 'Create a Book' %}</h1>
    <div class="row justify-content-center">
      <div class="col col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card p-3 pt-4">
          <form method='post' action=''>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center mt-4">
              <button class="btn btn-primary px-5">{% translate 'Create book' %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

learnity/core/templates/core/book_journey_read.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load core_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'Book Journey' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <div class="row justify-content-center text-center">
      <div class="col col-md-10 col-lg-9">
        <h1 class="h2 text-muted mb-4">
        {% if not user|is_owner_of_book_journey:book_journey %}   
          {% translate 'The book journey of' %} <b>{{ book_journey.created_by.name }}</b>
        {% else %}
          {% translate 'Your book journey' %}
        {% endif %}
        </h1>
        <p>{% translate 'through ' %} <b><a href="{% url 'core:book_read' pk=book_journey.book.pk %}">{{ book_journey.book.title }}</a></b></p>
      </div>
    </div>
  </div>
  <div class="container">
    <hr>
  </div>
  <div class="container">
    {% if book_journey.has_chapter_journeys or user|is_owner_of_book_journey:book_journey %}
    <div class="row justify-content-center">
      <div class="col col-md-10 col-lg-9">
        {% for chapter in book_journey.book.get_chapters %}
          {% if book_journey|has_chapter_journey_for_chapter:chapter %}
            {% include 'core/reusables/chapter_journey_card.html' with user=user book_journey=book_journey chapter=chapter chapter_journey=book_journey|get_chapter_journey_for_chapter:chapter %}
          {% elif user|is_owner_of_book_journey:book_journey %}
            {% include 'core/reusables/chapter_journey_start_card.html' with user=user book_journey=book_journey chapter=chapter %}
          {% endif %}
        {% endfor %}
      </div>
    </div>
    {% endif %}
  </div>
</section>
{% endblock %}

learnity/core/templates/core/book_list.html
{% extends 'site_base.html' %}

{% load i18n %}

{% block title %}
  {{ request.site.name }} - {% translate 'all books' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="text-center h2 text-muted mb-4">{% translate 'All Books' %}</h1>
    <div class="row justify-content-center">
      {% for book in book_list %}
        {% include 'core/reusables/book_list_card.html' with book=book %}
      {% empty %}
        <p>Nothing to see here</p>
      {% endfor %}
    </div>
    <div class="row justify-content-center actions text-center">
      <a
        class="btn btn-primary px-4"
        href="{% url 'core:book_create' %}"
      >
       {% translate 'Add new book' %}
      </a>
    </div>
  </div>
</section>
{% endblock %}

learnity/core/templates/core/book_read.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load static %}
{% load core_tags %}

{% block title %}
  {{ request.site.name }} - {{ book.title }}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col col-md-10 col-lg-9">
        <h1 class="text-center h2 text-muted mb-4">{% translate 'Book Details' %}</h1>
        <ul class="nav nav-tabs" id="id_book_detail_tablist" role="tablist">
          <li class="nav-item" role="presentation">
            <a class="nav-link {% if active_tab == 'summary' %}active{% endif %}" id="id_summary_tab" data-toggle="tab" href="#id_summary" role="tab" aria-controls="id_summary" aria-selected="true">{% translate 'Summary' %}</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class="nav-link {% if active_tab == 'chapters' %}active{% endif %}" id="id_chapters_tab" data-toggle="tab" href="#id_chapters" type="button" role="tab" aria-controls="id_chapters" aria-selected="false">{% translate 'Chapters' %}</a>
          </li>
        </ul>
        <div class="tab-content" id="id_book_detail_tablist_content">
          <div class="tab-pane fade {% if active_tab == 'summary' %}show active{% endif %}" id="id_summary" role="tabpanel" aria-labelledby="id_summary_tab">
            {% include 'core/reusables/book_summary.html' with book=book %}
          </div>
          <div class="tab-pane fade {% if active_tab == 'chapters' %}show active{% endif %}" id="id_chapters" role="tabpanel" aria-labelledby="id_chapters_tab">
            {% include 'core/reusables/chapter_list.html' with book=book %}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% if book.is_published %}
  <div class="container">
    <div class="row justify-content-center text-center">
      <div class="col col-md-10 col-lg-9">
        {% if user.is_authenticated and book|has_book_journey_by_user:user %}
        <h3 class="h6">Explore your book journey!</h3>
        {% with book|get_book_journey_by_user:user as book_journey_by_user %}
          <a
            href="{% url 'core:book_journey_read' pk=book_journey_by_user.pk %}"
            class="btn btn-success"
          >{% translate 'Explore' %}</a>
        {% endwith %}
        {% else %}
        <h3 class="h6">Start your journey with this book!</h3>
        <form method="post" action="{% url 'core:book_journey_create' book_pk=book.pk %}">
          {% csrf_token %}
          <button
            type="submit"
            class="btn btn-success"
          >
            {% translate 'Start book journey' %}
          </button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
  {% endif %}
</section>
{% endblock %}


{% block extra_js %}
<script type="text/javascript" src="{% static 'core/js/book_read.js' %}" ></script>
{% endblock %}

learnity/core/templates/core/book_update.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'update book' %}: {{ book.title }}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="text-center h2 text-muted mb-4">{% translate 'Update Book' %}</h1>
    <div class="row justify-content-center">
      <div class="col col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card p-3 pt-4">
          <form method='post' action=''>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center mt-4">
              <button class="btn btn-primary px-5">{% translate 'Update book' %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

learnity/core/templates/core/chapter_create.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'create a book chapter' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="text-center h2 text-muted mb-4">{% translate 'Create a Book Chapter' %}</h1>
    <p class="text-center mb-4"><b>Book:</b> <a href="{% url 'core:book_read' pk=book.pk %}">{{ book.title }}</a></p>
    <div class="row justify-content-center">
      <div class="col col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card p-3 pt-4">
          <form method='post' action=''>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center mt-4">
              <button class="btn btn-primary px-5">{% translate 'Create chapter' %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

learnity/core/templates/core/chapter_update.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'update chapter' %}: {{ book.title }}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="text-center h2 text-muted mb-4">{% translate 'Update Book Chapter' %}</h1>
     <p class="text-center mb-4"><b>Book:</b> <a href="{% url 'core:book_read' pk=book.pk %}">{{ book.title }}</a></p>
    <div class="row justify-content-center">
      <div class="col col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card p-3 pt-4">
          <form method='post' action=''>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center mt-4">
              <button class="btn btn-primary px-5">{% translate 'Update chapter' %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

learnity/core/templates/core/own_book_list.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load core_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'my books' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">

    <h1 class="text-center h2 text-muted mb-4">{% translate 'My Books' %}</h1>

    {% if messages %}
      {% for message in messages %}
        {% with message_tags=message.tags.split|to_set %}
          {% if 'book_delete' in message_tags %}
            <div
              class="alert alert-success alert-dismissible fade show mb-4"
              role="alert"
            >
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endif %}
        {% endwith %}
      {% endfor %}
    {% endif %}

    <div class="row justify-content-center">
      {% for book in book_list %}
        {% include 'core/reusables/book_list_card.html' with book=book %}
      {% empty %}
        <p>{% translate "It looks like you've not added any books to Learnity yet." %}</p>
      {% endfor %}
    </div>
    <div class="row justify-content-center actions text-center">
      <a
        class="btn btn-primary px-4"
        href="{% url 'core:book_create' %}"
      >
       {% translate 'Add new book' %}
      </a>
    </div>
  </div>
</section>
{% endblock %}