learnity/core/urls.py
from django.urls import path

from core.views import (
    BookCreateView,
    BookDeleteView,
    BookJourneyCreateView,
    BookJourneyReadView,
    BookListView,
    BookPublishView,
    BookReadView,
    BookUpdateView,
    ChapterCreateView,
    ChapterDeleteView,
    ChapterJourneyCreateView,
    ChapterJourneyReadView,
    ChapterUpdateView,
    OwnBookListView,
)

app_name = 'core'
urlpatterns = [
    # books
    path('books/', BookListView.as_view(), name='book_list'),
    path('books/own/', OwnBookListView.as_view(), name='own_book_list'),
    path('books/add', BookCreateView.as_view(), name='book_create'),
    path('books/<int:pk>/', BookReadView.as_view(), name='book_read'),
    path('books/<int:pk>/edit', BookUpdateView.as_view(), name='book_update'),
    path('books/<int:pk>/publish', BookPublishView.as_view(), name='book_publish'),
    path('books/<int:pk>/delete', BookDeleteView.as_view(), name='book_delete'),
    # chapters
    path('books/<int:book_pk>/chapters/add', ChapterCreateView.as_view(), name='chapter_create'),
    path('books/<int:book_pk>/chapters/<int:pk>/edit', ChapterUpdateView.as_view(), name='chapter_update'),
    path('books/<int:book_pk>/chapters/<int:pk>/delete', ChapterDeleteView.as_view(), name='chapter_delete'),
    # book-journeys
    path('book/<int:book_pk>/start-journey', BookJourneyCreateView.as_view(), name='book_journey_create'),
    path('book-journeys/<uuid:pk>/', BookJourneyReadView.as_view(), name='book_journey_read'),
    # chapter-journeys
    path(
        'book-journeys/<uuid:book_journey_pk>/chapters/<int:chapter_pk>/start-journey',
        ChapterJourneyCreateView.as_view(),
        name='chapter_journey_create',
    ),
    path('chapter-journeys/<uuid:pk>/', ChapterJourneyReadView.as_view(), name='chapter_journey_read'),
]

learnity/learnity/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.views import HomeView, LoginView, LogoutView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('home/', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
]

learnity/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Chapter


class ChapterCreateForm(forms.ModelForm):
    class Meta:
        fields = ['number', 'title', 'url', 'description']
        model = Chapter

    def __init__(self, *args, **kwargs):
        self.book = kwargs.pop('book')
        super().__init__(*args, **kwargs)

    def clean_number(self):
        cleaned_number = self.cleaned_data['number']
        for chapter in self.book.get_chapters():
            if chapter.number == cleaned_number:
                raise ValidationError(_('A chapter with this number already exists on the same book'), code='invalid')
        return cleaned_number

learnity/core/views.py
from django import forms
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.html import format_html, mark_safe
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, View

from .forms import ChapterCreateForm
from .models import Book, BookJourney, Chapter, ChapterJourney
from .utils import ticker


class BookCreateView(LoginRequiredMixin, CreateView):
    fields = ['title', 'subtitle', 'abstract', 'url', 'description']
    model = Book
    template_name = 'core/book_create.html'

    def form_valid(self, form):
        book = form.save(commit=False)
        book.created_at = ticker.now()
        book.created_by = self.request.user
        book.save()
        messages.success(
            self.request,
            format_html("{}: <b>{}</b>", mark_safe(_("You've just created a book")), book.title),
            extra_tags='book_create',
        )
        return HttpResponseRedirect(book.get_absolute_url())

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['abstract'].widget = forms.Textarea(
            attrs={'rows': 4, 'data-maxlength': form.fields['abstract'].max_length}
        )
        form.fields['description'].widget.attrs.update(rows=6)
        return form


class BookReadView(DetailView):
    queryset = Book.objects.filter(deleted_at__isnull=True).prefetch_related(
        'chapter_set', 'book_journey_set', 'created_by'
    )
    template_name = 'core/book_read.html'

    def get_object(self, queryset=None):
        book = super().get_object(queryset)
        if not book.is_published() and not book.can_be_published_by(self.request.user):
            raise PermissionDenied
        return book

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['active_tab'] = self.request.GET.get('tab', 'summary')
        return data


class OwnBookListView(LoginRequiredMixin, ListView):
    template_name = 'core/own_book_list.html'

    def get_queryset(self):
        return Book.objects.filter(deleted_at__isnull=True).filter(created_by_id=self.request.user.pk)


class BookListView(ListView):
    queryset = (
        Book.objects.filter(deleted_at__isnull=True).filter(published_at__isnull=False).select_related('created_by')
    )


class BookUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['title', 'subtitle', 'abstract', 'url', 'description']
    queryset = Book.objects.filter(deleted_at__isnull=True)
    template_name = 'core/book_update.html'

    def get_object(self, queryset=None):
        book = super().get_object(queryset)
        if not book.is_owned_by(self.request.user):
            raise PermissionDenied
        return book

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['abstract'].widget = forms.Textarea(
            attrs={'rows': 4, 'data-maxlength': form.fields['abstract'].max_length}
        )
        form.fields['description'].widget.attrs.update(rows=6)
        if self.object.is_published():
            form.fields['title'].disabled = True
            form.fields['subtitle'].disabled = True
        return form

    def form_valid(self, form):
        book = form.save()
        messages.success(
            self.request,
            format_html("{}: <b>{}</b>", mark_safe(_("You've just updated the book")), book.title),
            extra_tags='book_update',
        )
        return HttpResponseRedirect(book.get_absolute_url())


class BookPublishView(LoginRequiredMixin, UpdateView):
    fields = []
    queryset = Book.objects.filter(deleted_at__isnull=True)

    def get_object(self, queryset=None):
        book = super().get_object(queryset)
        if not book.can_be_published_by(self.request.user):
            raise PermissionDenied
        return book

    def get(self, request, *args, **kwargs):
        book = self.get_object()
        return HttpResponseRedirect(book.get_absolute_url())

    def post(self, request, *args, **kwargs):
        book = self.get_object()
        is_book_chapterless = not book.has_chapters()
        if book.is_published():
            messages.warning(
                self.request,
                mark_safe(_("You've already published this book!")),
                extra_tags='book_publish book_publish_warning',
            )
        else:
            if is_book_chapterless:
                messages.error(
                    self.request,
                    mark_safe(_("You cannot publish this book as it doesn't have any chapters, yet.")),
                    extra_tags='book_publish_error',
                )
            else:
                book.publish()
                messages.success(
                    self.request,
                    format_html("{}: <b>{}</b>", mark_safe(_("You've just published the book")), book.title),
                    extra_tags='book_publish',
                )

        success_url = book.get_absolute_url() + ('?tab=chapters' if is_book_chapterless else '')
        return HttpResponseRedirect(success_url)


class BookDeleteView(LoginRequiredMixin, DeleteView):
    queryset = Book.objects.filter(deleted_at__isnull=True)
    success_url = reverse_lazy('core:own_book_list')

    def get_object(self, queryset=None):
        book = super().get_object(queryset)
        if not book.can_be_deleted_by(self.request.user):
            raise PermissionDenied
        return book

    def get(self, request, *args, **kwargs):
        book = self.get_object()
        return HttpResponseRedirect(book.get_absolute_url())

    def delete(self, request, *args, **kwargs):
        book = self.get_object()
        book.delete()
        messages.success(
            self.request,
            format_html(
                "{}: <b>{}</b>",
                mark_safe(_("You've just deleted the book")),
                book.title,
            ),
            extra_tags='book_delete',
        )
        return HttpResponseRedirect(self.success_url)


class ChapterCreateView(LoginRequiredMixin, CreateView):
    form_class = ChapterCreateForm
    model = Chapter
    pk_url_kwarg = 'book_pk'
    template_name = 'core/chapter_create.html'

    def get_object(self, queryset=None):
        book = super().get_object(queryset=queryset)
        if not book.is_owned_by(self.request.user):
            raise PermissionDenied
        return book

    def get(self, request, *args, **kwargs):
        self.book = self.get_object(queryset=self.get_book_queryset())
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.book = self.get_object(queryset=self.get_book_queryset())
        return super().post(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['book'] = self.book
        return kwargs

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['book'] = self.book
        return data

    def form_valid(self, form):
        chapter = form.save(commit=False)
        chapter.created_at = ticker.now()
        chapter.book = self.book
        chapter.save()
        messages.success(
            self.request,
            format_html(
                "{}: <b>{}. {}</b>",
                mark_safe(_("You've just created a chapter")),
                chapter.number,
                chapter.title,
            ),
            extra_tags='chapter_create',
        )
        return HttpResponseRedirect(chapter.get_absolute_url())

    def get_book_queryset(self):
        return Book.objects.filter(deleted_at__isnull=True)


class ChapterUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['number', 'title', 'url', 'description']
    queryset = Chapter.objects.filter(deleted_at__isnull=True).select_related('book')
    template_name = 'core/chapter_update.html'

    def get_object(self, queryset=None):
        chapter = super().get_object(queryset=queryset)
        self.book = chapter.book
        if not chapter.book.is_owned_by(self.request.user):
            raise PermissionDenied
        return chapter

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['book'] = self.book
        return data

    def form_valid(self, form):
        chapter = form.save()
        messages.success(
            self.request,
            format_html(
                "{}: <b>{}. {}</b>",
                mark_safe(_("You've just updated the chapter")),
                chapter.number,
                chapter.title,
            ),
            extra_tags='chapter_update',
        )
        return HttpResponseRedirect(chapter.get_absolute_url())


class ChapterDeleteView(LoginRequiredMixin, DeleteView):
    queryset = Chapter.objects.filter(deleted_at__isnull=True).select_related('book')

    def get_object(self, queryset=None):
        chapter = super().get_object(queryset)
        if not chapter.can_be_deleted_by(self.request.user):
            raise PermissionDenied
        return chapter

    def get(self, request, *args, **kwargs):
        chapter = self.get_object()
        return HttpResponseRedirect(chapter.get_absolute_url())

    def delete(self, request, *args, **kwargs):
        chapter = self.get_object()
        chapter.delete()
        messages.success(
            self.request,
            format_html(
                "{}: <b>{}. {}</b>",
                mark_safe(_("You've just deleted the chapter")),
                chapter.number,
                chapter.title,
            ),
            extra_tags='chapter_delete',
        )
        success_url = chapter.book.get_absolute_url() + '?tab=chapters'

learnity/core/templates/core/reusables/book_list_card.html
{% load humanize %}
{% load i18n %}

{% load core_tags %}

<div class="col-sm-11 col-md-9 col-lg-7 col-xl-5 mb-4">
  <div class="card border-secondary bg-light w-100 h-100">
    <div class="card-header pb-2"><a href="{% url 'core:book_read' pk=book.pk %}">{{ book.title|truncatechars:40 }}</a></div>
    <div class="card-body text-secondary py-2">
      <p class="card-text mb-0">{{ book.abstract }}</p>
      {% if book.is_published %}
      <p class="mb-0 text-right">
        <small class="font-weight-bold">
          {% translate 'Added' %}: {{ book.published_at|naturaltime }} {% translate 'by' %} {% if user|is_owner_of_book:book %}<strong>You</strong>{% else %}{{ book.created_by.name }}{% endif %}
        </small>
      </p>
      {% endif %}
    </div>
  </div>
</div>

learnity/core/templates/core/reusables/book_summary.html
{% load i18n %}
{% load humanize %}
{% load core_tags %}

{% if messages %}
  {% for message in messages %}
    {% with message_tags=message.tags.split|to_set %}
      {% if 'book_create' in message_tags or 'book_update' in message_tags or 'book_publish' in message_tags %}
        <div
          class="alert
            {% if 'success' in message_tags %}
            alert-success
            {% elif 'warning' in message_tags %}
            alert-warning
            {% else %}
            alert-secondary
            {% endif %}
            alert-dismissible fade show mb-4"
          role="alert"
        >
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}
    {% endwith %}
  {% endfor %}
{% endif %}

{% if not book.has_chapters and user|can_publish_book:book and not book.is_published %}
  <div class="alert alert-info fade show mb-4" role="alert">
    Try adding chapters to this book so you can publish it.
    <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endif %}

<h2 class="header">{% translate 'Title' %}</h2>
<div class="content">{{ book.title }}</div>

{% if book.subtitle %}
<h2 class="header">{% translate 'Subtitle' %}</h2>
<div class="content">{{ book.subtitle }}</div>
{% endif %}

<h2 class="header">{% translate 'Abstract' %}</h2>
<p class="content">{{ book.abstract }}</p>

<h2 class="header">{% translate 'URL' %}</h2>
<p class="content"><a href="{{ book.url }}">{{ book.url }}</a></p>

<h2 class="header">{% translate 'Description' %}</h2>
<div class="content markdown">{{ book.description }}</div>

{% if book.is_published %}
<div>
  <b>{% translate 'Added' %}:</b>
  {{ book.published_at|naturaltime }} by
  {% if user|is_owner_of_book:book %}{% translate 'You' %}{% else %}{{ book.created_by.name }}{% endif %}
</div>
{% endif %}

{% include 'core/reusables/own_book_actions.html' with book=book user=user %}

learnity/core/templates/core/reusables/chapter_journey_card.html
{% load i18n %}

<div class="card mb-3 bg-light">
  <div class="card-body py-2">
    <h3 class="my-2 h6">{{chapter.number}} | {{ chapter.title }}</h3>
    <form method="post" action="{% url 'core:chapter_journey_create' book_journey_pk=book_journey.pk chapter_pk=chapter.pk %}">
      {% csrf_token %}
      <div class="d-flex justify-content-center">
        <a
          href="{% url 'core:chapter_journey_read' pk=chapter_journey.pk %}"
          class="btn btn-primary btn-sm"
        >
          {% translate 'Explore' %}
        </a>
      </div>
    </form>
  </div>
</div>

learnity/core/templates/core/reusables/chapter_journey_start_card.html
{% load i18n %}

<div class="card mb-3 bg-light">
  <div class="card-body py-2">
    <h3 class="my-2 h6">{{chapter.number}} | {{ chapter.title }}</h3>
    <form method="post" action="{% url 'core:chapter_journey_create' book_journey_pk=book_journey.pk chapter_pk=chapter.pk %}">
      {% csrf_token %}
      <div class="d-flex justify-content-center">
        <button
          type="submit"
          class="btn btn-primary btn-sm"
        >
          {% translate 'Start chapter journey' %}
        </button>
      </div>
    </form>
  </div>
</div>

learnity/core/templates/core/reusables/chapter_list.html
{% load i18n %}
{% load core_tags %}

{% if messages %}
  {% for message in messages %}
    {% with message_tags=message.tags.split|to_set %}
      {% if 'book_publish_error' in message_tags %}
        <div
          class="alert alert-danger alert-dismissible fade show mb-4"
          role="alert"
        >
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% elif 'chapter_create' in message_tags %}
        <div
          class="alert alert-success alert-dismissible fade show mb-4"
          role="alert"
        >
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% elif 'chapter_update' in message_tags %}
        <div
          class="alert alert-success alert-dismissible fade show mb-4"
          role="alert"
        >
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% elif 'chapter_delete' in message_tags %}
        <div
          class="alert alert-success alert-dismissible fade show mb-4"
          role="alert"
        >
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}
    {% endwith %}
  {% endfor %}
{% endif %}

<div>
  <b>Book:</b> <span>{{ book.title }}</span>
</div>

{% if book.has_chapters %}
<div class="accordion" id="id_chapters_accordion">
  {% for chapter in book.get_chapters %}
    {% include 'core/reusables/chapter_list_card.html' with chapter=chapter user=user %}
  {% endfor %}
</div>
{% else %}
<div class="alert alert-info mb-4" role="alert">
  {% translate "It looks like you've not yet created any chapters for this book." %}
</div>
{% endif %}

{% if user|is_owner_of_book:book %}
<div class="text-center">
  <a class="btn btn-primary" href="{% url 'core:chapter_create' book_pk=book.pk %}">Add chapter</a>
</div>
{% endif %}

learnity/core/templates/core/reusables/chapter_list_card.html
{% load i18n %}
{% load core_tags %}

<div class="card">
  <div class="card-header" id="id_heading-{{ chapter.number }}">
    <h3 class="mb-0">
      <button
        class="btn btn-link btn-block text-left"
        type="button"
        data-toggle="collapse"
        data-target="#id_collapse-{{ chapter.number }}"
        aria-expanded="false"
        aria-controls="id_collapse-{{ chapter.number }}"
      >Chapter {{chapter.number}}: {{ chapter.title }}</button>
    </h3>
  </div>

  <div
    id="id_collapse-{{ chapter.number }}"
    class="collapse"
    aria-labelledby="id_heading-{{ chapter.number }}"
    data-parent="#id_chapters_accordion"
  >
    <div class="card-body">
      <p><b>{% translate 'URL' %}:</b> {% if chapter.url %}<a href="{{ chapter.url }}">{{ chapter.url }}</a>{% else %}<span class="text-muted">N/A</span>{% endif %}</p>

      <div><b>{% translate 'Description' %}:</b></div>
      {% if not chapter.description %}
      <div class="text-muted">N/A</div>
      {% else %}
      <div class="markdown">{{ chapter.description }}</div>
      {% endif %}

      {% if user|is_owner_of_book:book %}
      <div class="d-flex justify-content-center align-items-center">
        <a
          class="btn btn-warning px-3 mx-1"
          href="{% url 'core:chapter_update' pk=chapter.pk book_pk=chapter.book_id %}"
        >
          {% translate 'Update' %}
        </a>
        <button
          id="id_delete-{{ chapter.number }}"
          type="button"
          class="btn btn-danger px-3 mx-1"
          data-toggle="modal"
          data-target="#id_delete_modal-{{ chapter.number }}"
          >
          {% translate 'Delete' %}
        </button>
        <div class="modal fade" id="id_delete_modal-{{ chapter.number }}" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <span class="text-danger">{% translate "You're about to delete the chapter" %}: <b>{{chapter.number}}. {{ chapter.title }}</b>!</span>
                <form method="post" action="{% url 'core:chapter_delete' pk=chapter.pk book_pk=chapter.book_id %}">
                  {% csrf_token %}
                  <div class="d-flex justify-content-end mt-4">
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-dismiss="modal"
                    >
                      {% translate 'Go back' %}
                    </button>
                    <button
                      type="submit"
                      class="btn btn-primary px-5 mx-3"
                    >
                      {% translate 'Confirm delete' %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>

learnity/core/templates/core/reusables/own_book_actions.html
{% load i18n %}
{% load core_tags %}

{% if user|is_owner_of_book:book %}
<div class="actions d-flex justify-content-center">

  <a
    class="btn btn-warning px-3 mx-1"
    href="{% url 'core:book_update' pk=book.pk %}"
  >
    {% translate 'Update' %}
  </a>

  <!-- Buttons -->
  {% if not book.is_published and book.has_chapters %}
  <button
    id="id_publish"
    type="button"
    class="btn btn-primary px-3 mx-1"
    data-toggle="modal"
    data-target="#id_publish_modal"
    >
    {% translate 'Publish' %}
  </button>
  {% endif %}
  <button
    id="id_delete"
    type="button"
    class="btn btn-danger px-3 mx-1"
    data-toggle="modal"
    data-target="#id_delete_modal"
    >
    {% translate 'Delete' %}
  </button>

  <!-- Modals -->
  {% if not book.is_published and book.has_chapters %}
  <div class="modal fade" id="id_publish_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>{% translate "You're about to publish the book" %} <b>{{ book.title }}</b></p>
          <form method="post" action="{% url 'core:book_publish' pk=book.pk %}">
            {% csrf_token %}
            <div class="d-flex justify-content-end mt-4">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
              >
                {% translate 'Go back' %}
              </button>
              <button
                type="submit"
                class="btn btn-primary px-5 mx-3"
              >
                {% translate 'Confirm publish' %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  <div class="modal fade" id="id_delete_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <span class="text-danger">{% translate "You're about to delete the book" %} <b>{{ book.title }}</b>!</span>
          <form method="post" action="{% url 'core:book_delete' pk=book.pk %}">
            {% csrf_token %}
            <div class="d-flex justify-content-end mt-4">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
              >
                {% translate 'Go back' %}
              </button>
              <button
                type="submit"
                class="btn btn-primary px-5 mx-3"
              >
                {% translate 'Confirm delete' %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>
{% endif %}